import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Nav, NavLink } from "@/components/Nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html lang="en">
      <body>
        {/* Navigation should be available across all pages */}
        <Nav>
          <NavLink href="/analytics">Dashboard</NavLink>
          <NavLink href="/portal">Portal</NavLink>
        </Nav>

        {/* Main content area where children will be rendered */}
        <div className="container my-6">{children}</div>
      </body>
    </html>
  );
}
